name: ci workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: export -p
      run:  export -p

    - name: brew install gnu-sed
      if:   matrix.os == 'macos-11.0'
      run:  brew install gnu-sed

    - name: brew install 
      run:  brew install automake autoconf libtool pkg-config make cmake meson gperf itstool tree lzip nasm doxygen protobuf xmlto

    - name: install ndk-pkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
        chmod u+x ndk-pkg
        mv ipkg $(brew --prefix)/bin

    - name: set ANDROID_NDK_HOME environment variable
      run:  echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle" >> $GITHUB_ENV

    - name: ndk-pkg version
      run:  ndk-pkg version

    - name: ndk-pkg update
      run:  ndk-pkg update

    - name: ndk-pkg install boost
      run:  ndk-pkg install boost

  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install ndk-pkg via homebrew
      run: |
        brew tap leleliu008/fpliu
        brew install ndk-pkg

    - name: ndk-pkg --version
      run:  ndk-pkg --version
