name: Ubuntu

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - run: bin/ndk-pkg --help
      - run: bin/ndk-pkg --version
      - run: bin/ndk-pkg --homedir
      - run: bin/ndk-pkg --homepage

      - run: bin/ndk-pkg ndkmanager ls-available

      - run: bin/ndk-pkg env

      - run: bin/ndk-pkg integrate zsh

      - run: bin/ndk-pkg update

      - run: git -C ~/.ndk-pkg/repos.d/offical checkout ${{ github.ref_name }}

      - run: bin/ndk-pkg search lib
      - run: bin/ndk-pkg search libzip

      - run: bin/ndk-pkg formula-repo list

      - run: bin/ndk-pkg formula view curl
      - run: bin/ndk-pkg formula view libzip --paging=never

      - run: bin/ndk-pkg info libzip
      - run: bin/ndk-pkg info libzip version
      - run: bin/ndk-pkg info libzip webpage
      - run: bin/ndk-pkg info libzip

      - run: bin/ndk-pkg depends libzip

      - run: bin/ndk-pkg depends libzip --format=list
      - run: bin/ndk-pkg depends libzip --format=json
      - run: bin/ndk-pkg depends libzip --format=dot
      - run: bin/ndk-pkg depends libzip --format=txt
      - run: bin/ndk-pkg depends libzip --format=png

      - run: bin/ndk-pkg depends libzip --format=list -o libzip-dependencies.list
      - run: bin/ndk-pkg depends libzip --format=json -o libzip-dependencies.json
      - run: bin/ndk-pkg depends libzip --format=dot  -o libzip-dependencies.dot
      - run: bin/ndk-pkg depends libzip --format=txt  -o libzip-dependencies.txt
      - run: bin/ndk-pkg depends libzip --format=png  -o libzip-dependencies.png

      - run: bin/ndk-pkg homepage
      - run: bin/ndk-pkg homepage libzip

      - run: bin/ndk-pkg install libzip


      - run: bin/ndk-pkg tree libzip

      - run: bin/ndk-pkg pack libzip tar.gz
      - run: bin/ndk-pkg pack libzip tar.xz
      - run: bin/ndk-pkg pack libzip tar.bz2
      - run: bin/ndk-pkg pack libzip 7z
      - run: bin/ndk-pkg pack libzip zip
      - run: bin/ndk-pkg pack libzip aar

      - run: bin/ndk-pkg ls-target-abis
      - run: bin/ndk-pkg ls-target-archs
      - run: bin/ndk-pkg ls-target-triples
      - run: bin/ndk-pkg ls-target-levels

      - run: bin/ndk-pkg ls-available
      - run: bin/ndk-pkg ls-installed
      - run: bin/ndk-pkg ls-outdated

      - run: bin/ndk-pkg is-available libzip
      - run: bin/ndk-pkg is-installed libzip
      - run: bin/ndk-pkg is-outdated  libzip || echo "not outdated"

      - run: bin/ndk-pkg uninstall libzip

      - run: bin/ndk-pkg fetch curl

      - run: bin/ndk-pkg upgrade @self

  install_via_homebrew:

    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - run: brew tap leleliu008/fpliu
      - run: brew install ndk-pkg

      - run: ndk-pkg --help
      - run: ndk-pkg --version
      - run: ndk-pkg --homedir
      - run: ndk-pkg --homepage

      - run: ndk-pkg env

      - run: ndk-pkg integrate zsh

      - run: ndk-pkg update

      - run: ndk-pkg search lib
      - run: ndk-pkg search libzip

      - run: ndk-pkg info libzip
      - run: ndk-pkg info libzip version
      - run: ndk-pkg info libzip webpage
      - run: ndk-pkg info libzip

      - run: ndk-pkg depends libzip

      - run: ndk-pkg depends libzip --format=list
      - run: ndk-pkg depends libzip --format=json
      - run: ndk-pkg depends libzip --format=dot
      - run: ndk-pkg depends libzip --format=txt
      - run: ndk-pkg depends libzip --format=png

      - run: ndk-pkg depends libzip --format=list -o libzip-dependencies.list
      - run: ndk-pkg depends libzip --format=json -o libzip-dependencies.json
      - run: ndk-pkg depends libzip --format=dot  -o libzip-dependencies.dot
      - run: ndk-pkg depends libzip --format=txt  -o libzip-dependencies.txt
      - run: ndk-pkg depends libzip --format=png  -o libzip-dependencies.png

      - run: ndk-pkg homepage
      - run: ndk-pkg homepage libzip

      - run: ndk-pkg install libzip

      - run: ndk-pkg tree libzip

      - run: bin/ndk-pkg pack libzip tar.gz
      - run: bin/ndk-pkg pack libzip tar.xz
      - run: bin/ndk-pkg pack libzip tar.bz2
      - run: bin/ndk-pkg pack libzip 7z
      - run: bin/ndk-pkg pack libzip zip
      - run: bin/ndk-pkg pack libzip aar

      - run: ndk-pkg formula-repo list
      - run: ndk-pkg formula view curl

      - run: ndk-pkg ls-target-abis
      - run: ndk-pkg ls-target-archs
      - run: ndk-pkg ls-target-triples
      - run: ndk-pkg ls-target-levels

      - run: ndk-pkg ls-available
      - run: ndk-pkg ls-installed
      - run: ndk-pkg ls-outdated

      - run: ndk-pkg is-available libzip
      - run: ndk-pkg is-installed libzip
      - run: ndk-pkg is-outdated  libzip || echo "not outdated"

      - run: ndk-pkg uninstall libzip

      - run: ndk-pkg fetch curl

      - run: ndk-pkg upgrade @self
