name: WSL

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        distribution: [Ubuntu-20.04, Debian, openSUSE-Leap-15.2]

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      # https://github.com/marketplace/actions/setup-wsl
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distribution }}

      - name: Use unix line endings
        shell: bash
        run: |
          # Github's actions/checkout@v2 when run on Windows mangles the line-endings to DOS-style
          # but we're running Linux *on top* of Windows, so we need to not mangle them!
          # https://github.com/actions/checkout/issues/135#issuecomment-602171132
          # https://github.com/actions/virtual-environments/issues/50#issuecomment-663920265
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - run: bin/ndk-pkg --help
      - run: bin/ndk-pkg --version
      - run: bin/ndk-pkg --homedir
      - run: bin/ndk-pkg --homepage

      - run: bin/ndk-pkg ndkmanager ls-available

      - run: bin/ndk-pkg env

      - run: bin/ndk-pkg integrate zsh

      - run: bin/ndk-pkg update

      - run: git -C ~/.ndk-pkg/repos.d/offical checkout ${{ github.ref_name }}

      - run: bin/ndk-pkg search lib
      - run: bin/ndk-pkg search libzip

      - run: bin/ndk-pkg info libzip
      - run: bin/ndk-pkg info libzip version
      - run: bin/ndk-pkg info libzip webpage
      - run: bin/ndk-pkg info libzip

      - run: bin/ndk-pkg depends libzip

      - run: bin/ndk-pkg depends libzip --format=list
      - run: bin/ndk-pkg depends libzip --format=json
      - run: bin/ndk-pkg depends libzip --format=dot
      - run: bin/ndk-pkg depends libzip --format=txt

      - run: bin/ndk-pkg depends libzip --format=list -o libzip-dependencies.list
      - run: bin/ndk-pkg depends libzip --format=json -o libzip-dependencies.json
      - run: bin/ndk-pkg depends libzip --format=dot  -o libzip-dependencies.dot
      - run: bin/ndk-pkg depends libzip --format=txt  -o libzip-dependencies.txt
      - run: bin/ndk-pkg depends libzip --format=png  -o libzip-dependencies.png

      - run: bin/ndk-pkg homepage
      - run: bin/ndk-pkg homepage libzip

      - run: bin/ndk-pkg install libzip


      - run: bin/ndk-pkg tree 21 libzip

      - run: bin/ndk-pkg pack libzip 21 tar.gz
      - run: bin/ndk-pkg pack libzip 21 tar.xz
      - run: bin/ndk-pkg pack libzip 21 tar.bz2
      - run: bin/ndk-pkg pack libzip 21 7z
      - run: bin/ndk-pkg pack libzip 21 zip
      - run: bin/ndk-pkg pack libzip 21 aar

      - run: bin/ndk-pkg formula-repo list
      - run: bin/ndk-pkg formula view curl

      - run: bin/ndk-pkg ls-target-abis
      - run: bin/ndk-pkg ls-target-archs
      - run: bin/ndk-pkg ls-target-triples
      - run: bin/ndk-pkg ls-target-levels

      - run: bin/ndk-pkg ls-available
      - run: bin/ndk-pkg ls-installed
      - run: bin/ndk-pkg ls-outdated

      - run: bin/ndk-pkg is-available libzip
      - run: bin/ndk-pkg is-installed libzip --min-sdk-api-level=21
      - run: bin/ndk-pkg is-outdated  libzip --min-sdk-api-level=21 || echo "not outdated"

      - run: bin/ndk-pkg uninstall libzip

      - run: bin/ndk-pkg fetch curl

      - run: bin/ndk-pkg upgrade @self
